"""pybyd - Async Python client for BYD vehicle telemetry API."""

from importlib.metadata import PackageNotFoundError, version

from pybyd.client import BydClient
from pybyd.config import BydConfig, DeviceProfile
from pybyd.exceptions import (
    BangcleError,
    BydApiError,
    BydAuthenticationError,
    BydConfigError,
    BydControlPasswordError,
    BydCryptoError,
    BydEndpointNotSupportedError,
    BydError,
    BydRateLimitError,
    BydRemoteControlError,
    BydSessionExpiredError,
    BydTransportError,
)
from pybyd.models import (
    AirCirculationMode,
    AuthToken,
    BatteryHeatParams,
    ChargingState,
    ChargingStatus,
    ClimateScheduleParams,
    ClimateStartParams,
    CommandAck,
    ConnectState,
    ControlCallOptions,
    ControlState,
    DoorOpenState,
    EnergyConsumption,
    GpsInfo,
    HvacStatus,
    LockState,
    OnlineState,
    PowerGear,
    PushNotificationState,
    RemoteControlResult,
    SeatClimateParams,
    SeatHeatVentState,
    SmartChargingSchedule,
    TirePressureUnit,
    Vehicle,
    VehicleRealtimeData,
    VehicleState,
    VerifyControlPasswordResponse,
    WindowState,
)

try:
    __version__ = version("pybyd")
except PackageNotFoundError:
    __version__ = "0+local"

__all__ = [
    "__version__",
    "AirCirculationMode",
    "AuthToken",
    "BatteryHeatParams",
    "BangcleError",
    "BydApiError",
    "BydAuthenticationError",
    "BydClient",
    "BydConfig",
    "BydConfigError",
    "BydControlPasswordError",
    "BydCryptoError",
    "BydEndpointNotSupportedError",
    "BydError",
    "BydRateLimitError",
    "BydRemoteControlError",
    "BydSessionExpiredError",
    "BydTransportError",
    "ChargingState",
    "ChargingStatus",
    "ClimateScheduleParams",
    "ClimateStartParams",
    "ControlCallOptions",
    "CommandAck",
    "ConnectState",
    "ControlState",
    "DeviceProfile",
    "DoorOpenState",
    "EnergyConsumption",
    "GpsInfo",
    "HvacStatus",
    "LockState",
    "OnlineState",
    "PowerGear",
    "PushNotificationState",
    "RemoteControlResult",
    "SeatClimateParams",
    "SeatHeatVentState",
    "SmartChargingSchedule",
    "TirePressureUnit",
    "Vehicle",
    "VehicleRealtimeData",
    "VehicleState",
    "VerifyControlPasswordResponse",
    "WindowState",
]
